before:
  hooks:
    - go mod tidy
builds:
  - id: cli
    main: ./cmd/cli
    binary:
      tnl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: server
    main: ./cmd/server
    binary:
      tnl-server
    env: CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - id: server
    goos: linux
    goarch: amd64
    ids:
      - server
    image_templates:
      - "justcompile/tnl:latest"
      - "justcompile/tnl:{{ .Tag }}"
      - "justcompile/tnl:{{ .Tag }}-{{ .Env.GO_VERSION }}"
      - "justcompile/tnl:v{{ .Major }}"
    dockerfile: Dockerfile.release
