version: '3.8'
services:
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "3333:80"
  web:
    build:
      context: .
    volumes:
      - ./:/go/src/github.com/justcompile/tnl
    ports:
      - "8080:8080"
      - "8081:8081"
